<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Description>MSTest integration for Notorious Test.</Description>
		<PackageId>NotoriousTest.MSTest</PackageId>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MSTest.TestFramework" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	  <ProjectReference Include="..\NotoriousTest\NotoriousTest.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="../artifacts/doggydog/win-x64/DoggyDog.exe" Pack="true" PackagePath="/tools/win-x64/" />
		<None Include="../artifacts/doggydog/win-x64/e_sqlite3.dll" Pack="true" PackagePath="/tools/win-x64/" />
		<None Include="../artifacts/doggydog/linux-x64/DoggyDog" Pack="true" PackagePath="/tools/linux-x64/" />
		<None Include="../artifacts/doggydog/linux-x64/libe_sqlite3.so" Pack="true" PackagePath="/tools/linux-x64/" />
		<None Include="build/NotoriousTest.MSTest.targets" Pack="true" PackagePath="build/" />
	</ItemGroup>
</Project>
