<Project>
  <PropertyGroup>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Brice SCHUMACHER</Authors>
    <RepositoryUrl>https://github.com/Notorious-Coding/Notorious-Test/</RepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <VersionPrefix>4.1.1</VersionPrefix>
  </PropertyGroup>
</Project>
