<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Description>Runtime provider used by NotoriousTest.</Description>
		<PackageId>NotoriousTest.Runtime</PackageId>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="System.Text.Json" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	</ItemGroup>
</Project>
