<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Description>Sqlite Infrastructure Registry used by NotoriousTest.</Description>
		<PackageId>NotoriousTest.SqlLiteRegistry</PackageId>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="System.Text.Json" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="NotoriousTest.UnitTests" />
		<InternalsVisibleTo Include="NotoriousTest.IntegrationTests" />
	</ItemGroup>
</Project>
