<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="System.Text.Json" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="NotoriousTest.UnitTests" />
		<InternalsVisibleTo Include="NotoriousTest.IntegrationTests" />
		<InternalsVisibleTo Include="NotoriousTest" />
		<InternalsVisibleTo Include="DoggyDog" />
	</ItemGroup>
</Project>
