<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Description>A Database integration with NotoriousTest.</Description>
		<PackageId>NotoriousTest.Database</PackageId>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Respawn" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
		<ProjectReference Include="..\NotoriousTest.TestContainers\NotoriousTest.TestContainers.csproj" />
	</ItemGroup>

</Project>
