<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NotoriousTest.SqlServer\NotoriousTest.SqlServer.csproj" />
    <ProjectReference Include="..\..\NotoriousTest.TUnit\NotoriousTest.TUnit.csproj" />
    <ProjectReference Include="..\..\NotoriousTest.Web\NotoriousTest.Web.csproj" />
    <ProjectReference Include="..\NotoriousTests.InfrastructuresSamples.TestWebApp\NotoriousTests.InfrastructuresSamples.TestWebApp.csproj" />
  </ItemGroup>
  <Import Project="./build/NotoriousTest.InfrastructuresSamples.MSTest.targets" />
  <ItemGroup>
    <None Update="Tables.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
