using NotoriousTest.Web;

using NotoriousTest.Sample.TUnit.Infrastructures;

using System.Reflection;

namespace NotoriousTest.Sample.TUnit.Environments
{
    // In fact, this is a test fixture (MSTest terminology: ClassInitialize/ClassCleanup).
    public class TestEnvironment : NotoriousTest.TUnit.Environment
    {
        public override Assembly CurrentAssembly => System.Reflection.Assembly.GetExecutingAssembly();

        // This is called at the start of the test campaign
        public override async Task ConfigureEnvironment()
        {
            // Adding all infrastructure needed for the test
            // Every environment generate an EnvironmentId that is unique for each test campaign
            AddInfrastructure<SqlServerInfrastructure>();

            // Here, we directly use the WebApplication without infrastructure.
            // It will be added to a default web application infrastructure
            // already configured to use environment Program class
            // and to consume the configuration generated by other infrastructures.
            this.AddWebApplication<TestWebApplication>();
        }
    }
}
