<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	  <ProjectReference Include="..\NotoriousTest\NotoriousTest.csproj" />
	</ItemGroup>
</Project>
