<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Description>A simple way to handle integration tests environment, with complete isolation of every tests.</Description>
		<PackageId>NotoriousTest</PackageId>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	  <ProjectReference Include="..\NotoriousTest.Internal.Runtime\NotoriousTest.Internal.Runtime.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	  <ProjectReference Include="..\NotoriousTest.Internal.SqlLiteRegistry\NotoriousTest.Internal.SqlLiteRegistry.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	  <ProjectReference Include="..\NotoriousTest.Internal.TestSettings\NotoriousTest.Internal.TestSettings.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	  <ProjectReference Include="..\NotoriousTest.Internal.Watchdog\NotoriousTest.Internal.Watchdog.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	</ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NotoriousTest.XUnit" />
    <InternalsVisibleTo Include="NotoriousTest.TUnit" />
    <InternalsVisibleTo Include="NotoriousTest.NUnit" />
    <InternalsVisibleTo Include="NotoriousTest.MSTest" />
  </ItemGroup>
</Project>