<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Description>A simple way to handle integration tests environment, with complete isolation of every tests.</Description>
		<PackageId>NotoriousTest</PackageId>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	  <ProjectReference Include="..\NotoriousTest.Runtime\NotoriousTest.Runtime.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	  <ProjectReference Include="..\NotoriousTest.SqlLiteRegistry\NotoriousTest.SqlLiteRegistry.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	  <ProjectReference Include="..\NotoriousTest.TestSettings\NotoriousTest.TestSettings.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	  <ProjectReference Include="..\NotoriousTest.Watchdog\NotoriousTest.Watchdog.csproj" PrivateAssets="contentfiles;analyzers;build;native"/>
	</ItemGroup>
</Project>