using Microsoft.AspNetCore.Mvc.Testing;
using NotoriousTest.Common.Environments;
using NotoriousTest.SqlServer;
using NotoriousTest.Web.Environments;
using NotoriousTests.InfrastructuresSamples.Infrastructures;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NotoriousTests.InfrastructuresSamples.Environments
{
    // In fact, this is a test fixture (xUnit terminology).
    public class TestEnvironment : AsyncWebEnvironment<Program>
    {
        // This is called at the start of the test campaign
        public override async Task ConfigureEnvironmentAsync()
        {
            // Adding all infrastructure needed for the test
            // Every environment generate an EnvironmentId that is unique for each test campaign
            await AddInfrastructure(new SqlServerInfrastructure());

            // Here, we directly use the WebApplication without infrastructure. 
            // It will be added to a default web application infrastructure
            // already configured to use environment Program class
            // and to consume the configuration generated by other infrastructures.
            await AddWebApplication(new TestWebApplication());
        }
    }
}
