using NotoriousTest.Web;

using NotoriousTests.InfrastructuresSamples.Infrastructures;

using System.Reflection;

using Xunit.Sdk;

namespace NotoriousTests.InfrastructuresSamples.Environments
{
    // In fact, this is a test fixture (xUnit terminology).
    public class TestEnvironment : NotoriousTest.XUnit.Environment
    {
        public TestEnvironment(IMessageSink sink) : base(sink)
        {
        }

        public override Assembly CurrentAssembly => Assembly.GetExecutingAssembly();

        // This is called at the start of the test campaign
        public override async Task ConfigureEnvironment()
        {
            // Adding all infrastructure needed for the test
            // Every environment generate an EnvironmentId that is unique for each test campaign
            AddInfrastructure<SqlServerInfrastructure>();

            // Here, we directly use the WebApplication without infrastructure. 
            // It will be added to a default web application infrastructure
            // already configured to use environment Program class
            // and to consume the configuration generated by other infrastructures.
            this.AddWebApplication<TestWebApplication>();
        }
    }
}
