using NotoriousTest.Web.Environments;

using NotoriousTests.InfrastructuresSamples.Infrastructures;

using System.Reflection;

namespace NotoriousTests.InfrastructuresSamples.Environments
{
    // In fact, this is a test fixture (xUnit terminology).
    public class TestEnvironment : AsyncWebEnvironment<Program>
    {
        public override Assembly CurrentAssembly => Assembly.GetExecutingAssembly();

        // This is called at the start of the test campaign
        public override async Task ConfigureEnvironmentAsync()
        {
            // Adding all infrastructure needed for the test
            // Every environment generate an EnvironmentId that is unique for each test campaign
            await AddInfrastructure(new SqlServerInfrastructure());

            await AddInfrastructure(new TestInfrastructure());
            // Here, we directly use the WebApplication without infrastructure. 
            // It will be added to a default web application infrastructure
            // already configured to use environment Program class
            // and to consume the configuration generated by other infrastructures.
            await AddWebApplication(new TestWebApplication());
        }
    }
}
