<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Description>Test Settings Provider used by NotoriousTest.</Description>
		<PackageId>NotoriousTest.TestSettings</PackageId>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
	</ItemGroup>
</Project>
