<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Description>NUnit integration for Notorious Test.</Description>
		<PackageId>NotoriousTest.NUnit</PackageId>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="NUnit" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
	  <ProjectReference Include="..\NotoriousTest\NotoriousTest.csproj" />
	</ItemGroup>
</Project>
