<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<PublishSingleFile>true</PublishSingleFile>
	<VersionPrefix>4.0.0</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotoriousTest.Core\NotoriousTest.Core.csproj" />
    <ProjectReference Include="..\NotoriousTest.SqlLiteRegistry\NotoriousTest.SqlLiteRegistry.csproj" />
    <ProjectReference Include="..\NotoriousTest.Watchdog\NotoriousTest.Watchdog.csproj" />
  </ItemGroup>

</Project>
