<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-2m69-gcr7-jv3q" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Microsoft.NET.Test.Sdk" />
	<PackageReference Include="NotoriousTest.SqlServer" />
	<PackageReference Include="NotoriousTest.Web" />
	<PackageReference Include="Respawn" />
	<PackageReference Include="xunit.v3" />
	<PackageReference Include="xunit.runner.visualstudio">
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="coverlet.collector">
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
    <PackageReference Include="NotoriousTest.XUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotoriousTest.Sample.TestWebApp\NotoriousTest.Sample.TestWebApp.csproj" />
  </ItemGroup>

</Project>