using Microsoft.VisualStudio.TestTools.UnitTesting;

using NotoriousTest.Web;

using NotoriousTests.InfrastructuresSamples.MSTest.Infrastructures;

using System.Reflection;

namespace NotoriousTests.InfrastructuresSamples.MSTest.Environments
{
    // In fact, this is a test fixture (MSTest terminology: ClassInitialize/ClassCleanup).
    public class TestEnvironment : NotoriousTest.MSTest.Environment
    {
        public TestEnvironment(TestContext testContext) : base(testContext)
        {
        }

        public override Assembly CurrentAssembly => Assembly.GetExecutingAssembly();

        // This is called at the start of the test campaign
        public override async Task ConfigureEnvironment()
        {
            // Adding all infrastructure needed for the test
            // Every environment generate an EnvironmentId that is unique for each test campaign
            AddInfrastructure<SqlServerInfrastructure>();

            // Here, we directly use the WebApplication without infrastructure.
            // It will be added to a default web application infrastructure
            // already configured to use environment Program class
            // and to consume the configuration generated by other infrastructures.
            this.AddWebApplication<TestWebApplication>();
        }
    }
}
